config/routes.rb
Rails.application.routes.draw do
  get 'microposts/index'

  root 'static_pages#home'
  get "contacts/new"
  get "users/show"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  devise_for :users, controllers: {
    :registrations => "registrations",
    :omniauth_callbacks => "omniauth_callbacks"
  }
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      get :reposting
    end
  end
  resources :likes, only: [:create, :destroy]

  resources :hashtags, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/views/shared/_content_search.html.erb
<p>content search</p>
<%= form_tag(yield(:path), method: :get, class: "search_form col-xs-13") do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, :class => "btn btn-info col-xs-4" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content">
    <%= render partial: 'shared/micropost_hashtag_conversion', locals: { micropost: feed_item } %>
    <%= render partial: 'shared/micropost_citations_view', locals: { micropost: feed_item } %>
  </span>
<% if feed_item.image? %>
  <% if Rails.env.production? %>
    <div><%= cl_image_tag(feed_item.image_url(:thumb)) %></div>
  <% else %>
    <div><%= image_tag feed_item.image_url(:thumb) %></div>
  <% end %>
<% end %>
  <span class="timestamp">
    <%= time_ago_in_words(feed_item.created_at) %>前
  </span>

  <div class="reaction_buttons_container">
    <%= render "likes/like", micropost: feed_item %>
    <%= render 'layouts/repostbutton' %>
    <%= render 'layouts/deletebutton', occurrence: feed_item if current_user == feed_item.user %>
  </div>
</li>

app/views/shared/_hashtag.html.erb
<table>
<% if params[:id] != "show_all" %>
  <thead>
    <tr>
      <th>ハッシュタグ</th>
    </tr>
  </thead>
<% end %>

  <tbody>
    <tr>
    <% if params[:id] != "show_all" %>
      <td><%= link_to 'すべてのタグ', micropost_path("show_all"), method: :get %></td>
    <% end %>
    </tr>
    <% @hashtags.each do |hashtag| %>
      <tr>
        <td>
          <%= link_to "\##{hashtag.name}", micropost_path(hashtag.name), method: :get %>
        <% if current_user.admin? %>
          | <%= link_to "delete", hashtag, method: :delete,
                                           data: { confirm: "You sure?" } %>
        <% end %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_micropost.html.erb
<li id="<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user), micropost.user %>
  <span class="user">
    <%= link_to micropost.user.name, micropost.user %>
  </span>
  <span class="content">
    <%= render partial: 'shared/micropost_hashtag_conversion', locals: { micropost: micropost } %>
    <%= render partial: 'shared/micropost_citations_view', locals: { micropost: micropost } %>
  </span>
<% if micropost.image? %>
  <% if Rails.env.production? %>
    <div><%= cl_image_tag(micropost.image_url(:thumb)) %></div>
  <% else %>
    <div><%= image_tag micropost.image_url(:thumb) %></div>
  <% end %>
<% end %>

  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前
  </span>

  <div class="reaction_buttons_container">
    <%= render "likes/like", micropost: micropost %>
    <%= render 'layouts/repostbutton' %>
    <%= render 'layouts/deletebutton', occurrence: micropost if current_user == micropost.user %>
  </div>
</li>

app/views/shared/_micropost_citations_view.html.erb
<% if micropost.citations %>
  <% micropost.citations.each do |c| %>
    <% c.source_id %>
    <br />
    <div class="panel panel-default repost-view-panel">
      <%= render partial: 'shared/micropost_hashtag_conversion', locals: { micropost: Micropost.find(c.source_id) } %>
      <br />
      <% user = User.find(Micropost.find(c.source_id).user_id) %>
      <%= link_to "@#{user.name}", user %>
      <% repostImage = Micropost.find(c.source_id) %>
      <% if repostImage.image? %>
        <% thumbnailSize = current_page?(root_path) ? repostImage.image_url(:thumb) : repostImage.image_url %>
        <% if Rails.env.production? %>
          <div><%= cl_image_tag(thumbnailSize) %></div>
        <% else %>
          <div><%= image_tag thumbnailSize %></div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "新しい投稿内容を入力..." %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-lg btn-primary postButtonDefault" %>
<% end %>

app/views/shared/_micropost_hashtag_conversion.html.erb
<% if micropost.hashtags.any? %>
  <%= micropost.content.gsub(/#.*$/, "") %>
  <p>
  <% micropost.hashtags.each do |hashtag| %>
    <% if micropost.content.match(/##{hashtag.name}/) %>
      <%= return_url("/microposts/#{hashtag.name}", "##{hashtag.name}").html_safe %>
    <% end %>
  <% end %>
  </p>
<% else %>
  <%= micropost.content %>
<% end %>

app/views/shared/_repost_form.html.erb
<% if @micropost %>
  <%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "新しい投稿内容を入力..." %>
    </div>

    <div class="well">
      <%= label :post_source, :content, :id =>"repost_source_content" %>
      <%= image_tag '', :id => 'repost_source_image' %>
      <%= hidden_field :post_source, :id, :id =>"repost_source_id" %>
    </div>

    <%= f.submit "投稿する", class: "btn btn-lg btn-primary postButtonDefault" %>
  <% end %>
<% end %>

app/views/shared/_search.html.erb
<!--  ユーザー検索  -->
<p>user search</p>
<%= form_tag(users_path, method: :get, class: "search_form col-xs-13") do %>
  <%= text_field_tag :search, @searched_text %>
  <%= submit_tag 'Search', :name => nil, :class => "btn btn-warning col-xs-4" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>