config/routes.rb
Rails.application.routes.draw do
  get 'microposts/index'

  root 'static_pages#home'
  get "contacts/new"
  get "users/show"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  devise_for :users, controllers: {
    :registrations => "registrations",
    :omniauth_callbacks => "omniauth_callbacks"
  }
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      get :reposting
    end
  end
  resources :likes, only: [:create, :destroy]

  resources :hashtags, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/views/layouts/_deletebutton.html.erb
<!-- モーダル表示用のボタン -->
<%= link_to occurrence, method: :delete, data: { confirm: "投稿を削除してよろしいですか？" },
                                      title: occurrence.content,
                                      class: 'btn trash_mark hv_mark_btn' do %>
  <%= fa_icon 'trash 2x' %>
  <span class="u-hiddenVisually">投稿を削除</span>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <% if Rails.env.development? %>
    <a href="http://twitter.com/">twitter.com</a>
    <% end %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!--  サイトロゴリンク  -->
    <%= link_to "Simple SNS", root_path, id: "logo" %>
    <!--   start to ヘッダーナビ表示   -->
    <nav>
      <!--   縮小画面時トグル表示   -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#e-t-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!--   End of 縮小画面時トグル表示   -->
      <!--   通常ヘッダーナビ表示   -->
      <div class="collapse navbar-collapse" id="e-t-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="first"><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if user_signed_in? %>
          <!--  ユーザーログイン時の表示項目  -->
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
          <% else %>
          <!--  非ログイン時の表示（Sign inのみ）  -->
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <!--   End of 通常ヘッダーナビ表示   -->
    </nav>
    <!-- End of ヘッダーナビ表示 -->
  </div>
</header>

app/views/layouts/_modal.html.erb
<!-- モーダル -->
<% if signed_in? %>
<div class="modal fade" id="repostModal" tabindex="-1" role="dialog" aria-labelledby="repostModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header img_cu_lo">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

        <h3 class="modal-title" id="repostModalLabel">_</h4>
        <%= link_to gravatar_for(current_user), current_user %>
        <%= current_user.name %>

      </div>
      <div class="modal-body">
        <%= render 'shared/repost_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>

<!--
<script>
//repost.js テスト用記述
</script>
-->

app/views/layouts/_repostbutton.html.erb
<% if signed_in? %>

<!-- モーダル表示用のボタン -->
<button type="button" class="btn img_cu_btn hv_mark_btn" data-toggle="modal" data-whatever="micropost" data-target="#repostModal">
  <%= fa_icon 'retweet 2x' %>
  <span class="u-hiddenVisually">引用投稿</span>
</button>


<% end %>

app/views/layouts/_shiv.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shiv' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  <body>
    <%= render 'layouts/modal' %>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert <%= bootstrap_class_for(key) %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>